import { SeedType } from '@/types';
import medicinalImg from '@/assets/plant-medicinal.jpg';
import fruitImg from '@/assets/plant-fruit.jpg';
import purifierImg from '@/assets/plant-purifier.jpg';

export const SEED_CATALOG: SeedType[] = [
  {
    id: 'seed-1',
    name: 'Neem Tree',
    category: 'purifier',
    description: 'Excellent air purifier, reduces CO2 by 48 lbs/year',
    price: 15,
    plantingReward: 5,
    monthlyReward: 3,
    yieldingReward: 25,
    environmentalImpact: 95,
    growthDuration: 18,
    imageUrl: purifierImg,
  },
  {
    id: 'seed-2',
    name: 'Tulsi (Holy Basil)',
    category: 'medicinal',
    description: 'Medicinal plant with immune-boosting properties',
    price: 10,
    plantingReward: 4,
    monthlyReward: 2.5,
    yieldingReward: 20,
    environmentalImpact: 65,
    growthDuration: 6,
    imageUrl: medicinalImg,
  },
  {
    id: 'seed-3',
    name: 'Mango Tree',
    category: 'fruit',
    description: 'Fruit-bearing tree, high yield value',
    price: 20,
    plantingReward: 6,
    monthlyReward: 4,
    yieldingReward: 40,
    environmentalImpact: 85,
    growthDuration: 24,
    imageUrl: fruitImg,
  },
  {
    id: 'seed-4',
    name: 'Tomato Plant',
    category: 'vegetable',
    description: 'Fast-growing vegetable, quick rewards',
    price: 8,
    plantingReward: 3,
    monthlyReward: 2,
    yieldingReward: 15,
    environmentalImpact: 50,
    growthDuration: 4,
    imageUrl: 'https://images.unsplash.com/photo-1592841200221-a6898f307baa?w=400&h=400&fit=crop',
  },
  {
    id: 'seed-5',
    name: 'Bamboo',
    category: 'purifier',
    description: 'Fastest CO2 absorber, 35% more oxygen than trees',
    price: 12,
    plantingReward: 5,
    monthlyReward: 3.5,
    yieldingReward: 30,
    environmentalImpact: 100,
    growthDuration: 12,
    imageUrl: 'https://images.unsplash.com/photo-1523348837708-15d4a09cfac2?w=400&h=400&fit=crop',
  },
  {
    id: 'seed-6',
    name: 'Moringa',
    category: 'medicinal',
    description: 'Superfood plant with high nutritional value',
    price: 18,
    plantingReward: 5,
    monthlyReward: 3,
    yieldingReward: 35,
    environmentalImpact: 75,
    growthDuration: 8,
    imageUrl: 'https://images.unsplash.com/photo-1598170845058-32b9d6a5da37?w=400&h=400&fit=crop',
  },
];

export const BADGES = [
  { id: 'badge-1', name: 'First Sprout', description: 'Plant your first tree', icon: '🌱' },
  { id: 'badge-2', name: 'Green Thumb', description: 'Maintain 5 healthy plants', icon: '👍' },
  { id: 'badge-3', name: 'Eco Warrior', description: 'Earn 100+ environmental points', icon: '🌍' },
  { id: 'badge-4', name: 'Consistent Caretaker', description: '30-day check-in streak', icon: '📅' },
  { id: 'badge-5', name: 'First Harvest', description: 'Your first plant reaches yielding stage', icon: '🌾' },
  { id: 'badge-6', name: 'Money Tree', description: 'Earn $100 in total rewards', icon: '💰' },
];
